### ISSUE TITLE
Is it possible to change the rootfs directory?

### ISSUE THREAD

**Issue by nulceck** [map220v/android_kernel_samsung_a51nsxx#1]
I would like to change the rootfs location directory, since the /data partition is limited in size, I lack this. I would like to move rootfs.img to any other place, for example to a memory card or internal memory.

**Comment by map220v** [comment]
Unpack Linux11.img using AIK(android image kitchen).
In "ramdisk/init_functions" change(at line 488)  "mount /dev/sda32 /data" to "mount /dev/mmcblk0p1 /data" it should make init script use sdcard instead of userdata partition.

I changed it to sdcard in this boot.img: [Linux11.zip](https://github.com/map220v/kernel_samsung_a51-linux/files/8793951/Linux11.zip)
